appName: SeizeTheMeans-backend # This value was modified by the initial-setup python script

deployment:
  image:
    repository: tobsss/SeizeTheMeans-backend # This value was modified by the initial-setup python script