apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: SeizeTheMeans-front-stage # This value was modified by the initial-setup python script
  namespace: argocd
spec:
  destination:
    namespace: SeizeTheMeans-stage # This value was modified by the initial-setup python script
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/my-app/frontend
    helm:
      valueFiles:
        - environments/values-stage.yaml
    repoURL: https://github.com/tob-ss/automate-all-the-things.git # This value was modified by the initial-setup python script
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true